### PR TITLE
SLING-11733: Add rule for defining a custom user-agent

### PR DESCRIPTION
**Pull request by Kronnox**
Adds a custom JUnit rule for adjusting the user agent.

### CODE REVIEW

**Comment by enapps-enorman** [comment]
I don't have any specific concerns with this solution.  I'd just point out that this solution would be only for consumers who are still using junit4.

For those that have migrated to junit5, a [BeforeEachCallback](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/BeforeEachCallback.html) extension would be needed instead of this new rule.

However, making a fork of the sling-org-apache-sling-testing-rules project that is compatible with junit5 is a larger problem and should probably be considered separately.

**Comment by Kronnox** [comment]
> I don't have any specific concerns with this solution. I'd just point out that this solution would be only for consumers who are still using junit4.
> 
> For those that have migrated to junit5, a [BeforeEachCallback](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/BeforeEachCallback.html) extension would be needed instead of this new rule.
> 
> However, making a fork of the sling-org-apache-sling-testing-rules project that is compatible with junit5 is a larger problem and should probably be considered separately.

As everything else is still based on junit4 as well I opted for consistency with this PR. So yeah, as you've already mentioned yourself the junit5 migration would be a larger topic on its own.

**Comment by enapps-enorman** [comment]
> junit5 migration would be a larger topic on its own

FYI: I opened the SLING-11708 ticket for tracking junit5 compatibility separately.

**Comment by rombert** [comment]
@Kronnox - please open a new Sling Jira issue, SLING-11679 is already used for the testing clients and is closed.

@joerghoh - you cut the testing clients release which included SLING-11679, do you have enough context to review this PR as well?

**Comment by Kronnox** [comment]
> please open a new Sling Jira issue, SLING-11679 is already used for the testing clients and is closed.
@rombert done.

**Comment by joerghoh** [comment]
@Kronnox Do you think that any inline documentation is necessary/helpful?

**Review by joerghoh — APPROVED** [review]

**Comment by rombert** [comment]
Thanks for the contribution @Kronnox !

**Comment by rombert** [comment]
I tried to prepare the release but the tests consistently fail for me locally with

```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   FilterRuleExcludeCategoryTest.testIgnoreIfPropExistsandExcludedCategoryExists:61 Test should be Ignored
[INFO] 
[ERROR] Tests run: 63, Failures: 1, Errors: 0, Skipped: 26
```

I tried Java 8, 11, 17, latest check

```
Apache Maven 3.8.6 (SUSE 3.8.6-2.1)
Maven home: /usr/share/maven
Java version: 1.8.0_352, vendor: IcedTea, runtime: /usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.0.12-1-default", arch: "amd64", family: "unix"
```

@joerghoh - do the test pass for you? I see Jenkins is happy /cc @dulvac

**Comment by joerghoh** [comment]
works fine here.
```
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /opt/homebrew/Cellar/maven/3.8.7/libexec
Java version: 11.0.15, vendor: Eclipse Adoptium, runtime: /Users/joerg/java/jdk-11.0.15+10-amd64/Contents/Home
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "13.1", arch: "x86_64", family: "mac"
```

**Pull request merged**
